/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SearchForm {
    }
}
declare global {
    interface HTMLSearchFormElement extends Components.SearchForm, HTMLStencilElement {
    }
    var HTMLSearchFormElement: {
        prototype: HTMLSearchFormElement;
        new (): HTMLSearchFormElement;
    };
    interface HTMLElementTagNameMap {
        "search-form": HTMLSearchFormElement;
    }
}
declare namespace LocalJSX {
    interface SearchForm {
    }
    interface IntrinsicElements {
        "search-form": SearchForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "search-form": LocalJSX.SearchForm & JSXBase.HTMLAttributes<HTMLSearchFormElement>;
        }
    }
}
