/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GithubCard {
        "user": string;
    }
    interface SearchForm {
    }
}
declare global {
    interface HTMLGithubCardElement extends Components.GithubCard, HTMLStencilElement {
    }
    var HTMLGithubCardElement: {
        prototype: HTMLGithubCardElement;
        new (): HTMLGithubCardElement;
    };
    interface HTMLSearchFormElement extends Components.SearchForm, HTMLStencilElement {
    }
    var HTMLSearchFormElement: {
        prototype: HTMLSearchFormElement;
        new (): HTMLSearchFormElement;
    };
    interface HTMLElementTagNameMap {
        "github-card": HTMLGithubCardElement;
        "search-form": HTMLSearchFormElement;
    }
}
declare namespace LocalJSX {
    interface GithubCard {
        "user": string;
    }
    interface SearchForm {
    }
    interface IntrinsicElements {
        "github-card": GithubCard;
        "search-form": SearchForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "github-card": LocalJSX.GithubCard & JSXBase.HTMLAttributes<HTMLGithubCardElement>;
            "search-form": LocalJSX.SearchForm & JSXBase.HTMLAttributes<HTMLSearchFormElement>;
        }
    }
}
